# Generated by Django 4.0.5 on 2022-07-02 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itsp', '0004_cleaning_date_alter_cleaning_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='wingcleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=50)),
                ('Room', models.CharField(max_length=20)),
                ('shift', models.CharField(choices=[('1', 'morning'), ('2', 'Afternoon'), ('3', 'Evening')], max_length=20)),
                ('timeapply', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
